### ISSUE TITLE
error in Main_SNARE_seq.py : ValueError: The parameter scale has invalid values

### ISSUE THREAD

**Issue by fengfengup** [cmzuo11/DCCA#1]
There is an error in > DCCA/MVAE_cycleVAE.py(124)return_loss(), which seems to indicate that the data has a negative value. And what I have doned is just to run "python Main_SNARE_seq.py" , which uses example_test data. 
I don't know why this happens. Is there a problem with the data or the version of the torch(my version: Python 3.8.5, torch 1.9)?

### Bug:
(base) user@max:~/codeFile/DCCA/DCCA$ python Main_SNARE_seq.py
Successfully preprocessed 500 genes and 1047 cells.
scRNA-ARI: 0.174 NMI: 0.231 scEpigenomics-ARI: -0.003 NMI: 0.016
> DCCA/MVAE_cycleVAE.py(124)return_loss()
-> kl_divergence_z  =  kl( Normal(mean_1, logvar_1),
(Pdb) mean_1[:5,:5]
tensor([[ 0.4193,  0.7762,  0.2410,  0.3056],
        [-0.2368, -0.2553,  0.5486, -0.5138],
        [ 0.2578,  0.3257, -0.0905, -0.1029],
        [ 0.2327,  0.7521, -0.0562, -0.0971],
        [-0.3688, -0.0784, -0.7044, -0.7771]], device='cuda:0',
       grad_fn=< SliceBackward >)
(Pdb) logvar_1[:5,:5]
tensor([[-0.0222,  0.0807,  0.2321,  0.6902],
        [-0.1965,  0.6097,  0.3196,  0.1595],
        [-0.1623,  0.4670,  0.0327,  0.3600],
        [-0.2922,  0.3439,  0.0080,  0.1602],
        [-0.1674,  0.2868,  0.3996,  0.4643]], device='cuda:0',
       grad_fn=< SliceBackward >)
(Pdb) c
Traceback (most recent call last):
  File "Main_SNARE_seq.py", line 123, in <module>
    train_with_argas(args)
  File "Main_SNARE_seq.py", line 90, in train_with_argas
    NMI_score1, ARI_score1, NMI_score2, ARI_score2  =  model.fit_model(train_loader, test_loader, total_loader, "RNA" )
  File "/DCCA/DCCA/MVAE_cycleVAE.py", line 471, in fit_model
    self.model1.fit( train_loader, test_loader, total_loader, self.model2, self.args, self.attention, used_cycle, 0, first, self.attention_loss  )
  File "/DCCA/DCCA/MVAE_cycleVAE.py", line 194, in fit
    loss1, kl_divergence_z, atten_loss1 = self.return_loss( X1, X1_raw, None, None, None, None, 
  File "/DCCA/DCCA/MVAE_cycleVAE.py", line 124, in return_loss
    kl_divergence_z  =  kl( Normal(mean_1, logvar_1), 
  File "/miniconda3/lib/python3.8/site-packages/torch/distributions/normal.py", line 50, in __ init __
    super(Normal, self).__init__(batch_shape, validate_args=validate_args)
  File "/miniconda3/lib/python3.8/site-packages/torch/distributions/distribution.py", line 53, in __ init __
    raise ValueError("The parameter {} has invalid values".format(param))
ValueError: The parameter scale has invalid values

:blush::blush::blush:
Thank you in advance ! @cmzuo11

**Comment by cmzuo11** [comment]
> There is an error in > DCCA/MVAE_cycleVAE.py(124)return_loss(), which seems to indicate that the data has a negative value. And what I have doned is just to run "python Main_SNARE_seq.py" , which uses example_test data.
> I don't know why this happens. Is there a problem with the data or the version of the torch(my version: Python 3.8.5, torch 1.9)?
> 
> ### Bug:
> (base) user@max:~/codeFile/DCCA/DCCA$ python Main_SNARE_seq.py
> Successfully preprocessed 500 genes and 1047 cells.
> scRNA-ARI: 0.174 NMI: 0.231 scEpigenomics-ARI: -0.003 NMI: 0.016
> 
> > DCCA/MVAE_cycleVAE.py(124)return_loss()
> > -> kl_divergence_z  =  kl( Normal(mean_1, logvar_1),
> > (Pdb) mean_1[:5,:5]
> > tensor([[ 0.4193,  0.7762,  0.2410,  0.3056],
> > [-0.2368, -0.2553,  0.5486, -0.5138],
> > [ 0.2578,  0.3257, -0.0905, -0.1029],
> > [ 0.2327,  0.7521, -0.0562, -0.0971],
> > [-0.3688, -0.0784, -0.7044, -0.7771]], device='cuda:0',
> > grad_fn=< SliceBackward >)
> > (Pdb) logvar_1[:5,:5]
> > tensor([[-0.0222,  0.0807,  0.2321,  0.6902],
> > [-0.1965,  0.6097,  0.3196,  0.1595],
> > [-0.1623,  0.4670,  0.0327,  0.3600],
> > [-0.2922,  0.3439,  0.0080,  0.1602],
> > [-0.1674,  0.2868,  0.3996,  0.4643]], device='cuda:0',
> > grad_fn=< SliceBackward >)
> > (Pdb) c
> > Traceback (most recent call last):
> > File "Main_SNARE_seq.py", line 123, in 
> > train_with_argas(args)
> > File "Main_SNARE_seq.py", line 90, in train_with_argas
> > NMI_score1, ARI_score1, NMI_score2, ARI_score2  =  model.fit_model(train_loader, test_loader, total_loader, "RNA" )
> > File "/DCCA/DCCA/MVAE_cycleVAE.py", line 471, in fit_model
> > self.model1.fit( train_loader, test_loader, total_loader, self.model2, self.args, self.attention, used_cycle, 0, first, self.attention_loss  )
> > File "/DCCA/DCCA/MVAE_cycleVAE.py", line 194, in fit
> > loss1, kl_divergence_z, atten_loss1 = self.return_loss( X1, X1_raw, None, None, None, None,
> > File "/DCCA/DCCA/MVAE_cycleVAE.py", line 124, in return_loss
> > kl_divergence_z  =  kl( Normal(mean_1, logvar_1),
> > File "/miniconda3/lib/python3.8/site-packages/torch/distributions/normal.py", line 50, in __ init __
> > super(Normal, self).**init**(batch_shape, validate_args=validate_args)
> > File "/miniconda3/lib/python3.8/site-packages/torch/distributions/distribution.py", line 53, in __ init __
> > raise ValueError("The parameter {} has invalid values".format(param))
> > ValueError: The parameter scale has invalid values
> 
> 😊😊😊
> Thank you in advance ! @cmzuo11



> There is an error in > DCCA/MVAE_cycleVAE.py(124)return_loss(), which seems to indicate that the data has a negative value. And what I have doned is just to run "python Main_SNARE_seq.py" , which uses example_test data.
> I don't know why this happens. Is there a problem with the data or the version of the torch(my version: Python 3.8.5, torch 1.9)?
> 
> ### Bug:
> (base) user@max:~/codeFile/DCCA/DCCA$ python Main_SNARE_seq.py
> Successfully preprocessed 500 genes and 1047 cells.
> scRNA-ARI: 0.174 NMI: 0.231 scEpigenomics-ARI: -0.003 NMI: 0.016
> 
> > DCCA/MVAE_cycleVAE.py(124)return_loss()
> > -> kl_divergence_z  =  kl( Normal(mean_1, logvar_1),
> > (Pdb) mean_1[:5,:5]
> > tensor([[ 0.4193,  0.7762,  0.2410,  0.3056],
> > [-0.2368, -0.2553,  0.5486, -0.5138],
> > [ 0.2578,  0.3257, -0.0905, -0.1029],
> > [ 0.2327,  0.7521, -0.0562, -0.0971],
> > [-0.3688, -0.0784, -0.7044, -0.7771]], device='cuda:0',
> > grad_fn=< SliceBackward >)
> > (Pdb) logvar_1[:5,:5]
> > tensor([[-0.0222,  0.0807,  0.2321,  0.6902],
> > [-0.1965,  0.6097,  0.3196,  0.1595],
> > [-0.1623,  0.4670,  0.0327,  0.3600],
> > [-0.2922,  0.3439,  0.0080,  0.1602],
> > [-0.1674,  0.2868,  0.3996,  0.4643]], device='cuda:0',
> > grad_fn=< SliceBackward >)
> > (Pdb) c
> > Traceback (most recent call last):
> > File "Main_SNARE_seq.py", line 123, in 
> > train_with_argas(args)
> > File "Main_SNARE_seq.py", line 90, in train_with_argas
> > NMI_score1, ARI_score1, NMI_score2, ARI_score2  =  model.fit_model(train_loader, test_loader, total_loader, "RNA" )
> > File "/DCCA/DCCA/MVAE_cycleVAE.py", line 471, in fit_model
> > self.model1.fit( train_loader, test_loader, total_loader, self.model2, self.args, self.attention, used_cycle, 0, first, self.attention_loss  )
> > File "/DCCA/DCCA/MVAE_cycleVAE.py", line 194, in fit
> > loss1, kl_divergence_z, atten_loss1 = self.return_loss( X1, X1_raw, None, None, None, None,
> > File "/DCCA/DCCA/MVAE_cycleVAE.py", line 124, in return_loss
> > kl_divergence_z  =  kl( Normal(mean_1, logvar_1),
> > File "/miniconda3/lib/python3.8/site-packages/torch/distributions/normal.py", line 50, in __ init __
> > super(Normal, self).**init**(batch_shape, validate_args=validate_args)
> > File "/miniconda3/lib/python3.8/site-packages/torch/distributions/distribution.py", line 53, in __ init __
> > raise ValueError("The parameter {} has invalid values".format(param))
> > ValueError: The parameter scale has invalid values
> 
> 😊😊😊
> Thank you in advance ! @cmzuo11

Dear,

Thanks so much for your interest in the DCCA model. I have run DCCA on my server, and got an accurate result. 

Based on your problem, I have the following interpretations: (1) the variable 'log_var' indicates the log of variable, so it is accurate for the variable has negative values sometimes; (2) I just used the linear layer to calculate mean and log_var, both variables should have negative values. 

In addition, based on your error, I think it should be the problem within the version of torch or python '/miniconda3/lib/python3.8/site-packages/torch/distributions/normal.py'. Can you please try torch 1.6.0 and Python 3.6.12?

Best regards,
chunman

**Comment by fengfengup** [comment]
Problem solved！Thank you.  :blush:
Just use the the same version (torch 1.6.0 and Python 3.6.12), there are no errors.
